name: Build and deploy code

on: [push, pull_request]


jobs:
  job1:
    env:
      SECRET_KEY=8072dc65800d9d5d1e4bcb6a7c0744ec9076628263f6fa1c51bb172bc8425273
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=30
      DATABASE_USERNAME=postgres.dvgaegpujvioxbzpuumm
      DATABASE_PASSWORD=Ry%40ng%23200%266th
      DATABASE_NAME=postgres
      PORT=6543
      HOST=aws-0-eu-west-1.pooler.supabase.com

    runs-on: ubuntu-latest
    steps:
      - name: Pull git repo
        uses: actions/checkout@v7
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all requirements
        run: pip install -r requirements.txt
      - name: run tests
        run: |
          pip install pytest
          pytest -v -s